use anyhow::Result;
use chrono::Utc;
use std::path::PathBuf;

use crate::embedding::{Embedder, HashEmbedder};
use crate::event::MemoryEntry;
use crate::storage::Storage;

/// Whisper — context injection engine.
/// Generates a CONTEXT.md file with the most relevant memories for the current project.
/// Claude Code picks this up via memory files or CLAUDE.md includes.
pub struct Whisper {
    output_path: PathBuf,
    max_recent: usize,
    max_decisions: usize,
    max_feedback: usize,
}

impl Whisper {
    pub fn new(output_path: PathBuf) -> Self {
        Self {
            output_path,
            max_recent: 10,
            max_decisions: 10,
            max_feedback: 5,
        }
    }

    /// Generate context file from current memory state.
    /// Called on session start and periodically.
    pub fn generate(&self, storage: &Storage) -> Result<String> {
        let now = Utc::now();
        let mut sections: Vec<String> = Vec::new();

        // Header
        sections.push(format!(
            "# Mnemonic Context\n\n_Auto-generated: {}_\n",
            now.format("%Y-%m-%d %H:%M UTC")
        ));

        // Recent decisions (highest value)
        let all_recent = storage.recent(50)?;

        let decisions: Vec<&MemoryEntry> = all_recent
            .iter()
            .filter(|e| e.memory_type == crate::event::MemoryType::Decision)
            .take(self.max_decisions)
            .collect();

        if !decisions.is_empty() {
            sections.push("## Key Decisions\n".into());
            for entry in &decisions {
                let age = format_age(now, entry.timestamp);
                sections.push(format!(
                    "- **{}** ({}) — {}",
                    entry.title,
                    age,
                    truncate(&entry.content, 120),
                ));
                if !entry.tags.is_empty() {
                    sections.push(format!("  _tags: {}_", entry.tags.join(", ")));
                }
            }
            sections.push(String::new());
        }

        // User feedback / corrections (must not repeat mistakes)
        let feedback: Vec<&MemoryEntry> = all_recent
            .iter()
            .filter(|e| e.memory_type == crate::event::MemoryType::Feedback)
            .take(self.max_feedback)
            .collect();

        if !feedback.is_empty() {
            sections.push("## User Feedback (DO NOT repeat these mistakes)\n".into());
            for entry in &feedback {
                let age = format_age(now, entry.timestamp);
                sections.push(format!(
                    "- **{}** ({}) — {}",
                    entry.title,
                    age,
                    truncate(&entry.content, 120)
                ));
            }
            sections.push(String::new());
        }

        // Recent activity
        let recent: Vec<&MemoryEntry> = all_recent
            .iter()
            .filter(|e| {
                e.memory_type != crate::event::MemoryType::Decision
                    && e.memory_type != crate::event::MemoryType::Feedback
            })
            .take(self.max_recent)
            .collect();

        if !recent.is_empty() {
            sections.push("## Recent Activity\n".into());
            for entry in &recent {
                let age = format_age(now, entry.timestamp);
                sections.push(format!(
                    "- [{}] **{}** ({}, importance: {:.1})",
                    entry.memory_type, entry.title, age, entry.importance
                ));
            }
            sections.push(String::new());
        }

        // Stats
        if let Ok(stats) = storage.stats() {
            sections.push(format!(
                "---\n_Total memories: {} | Generated by mnemonic_",
                stats.total
            ));
        }

        let content = sections.join("\n");

        // Write to file
        self.write_file(&content)?;

        Ok(content)
    }

    /// Generate context relevant to a specific topic (semantic search)
    pub fn generate_for_topic(
        &self,
        storage: &Storage,
        topic: &str,
        limit: usize,
    ) -> Result<String> {
        let now = Utc::now();
        let embedder = HashEmbedder::new();
        let query_emb = embedder.embed(topic)?;
        let similar = storage.find_similar(&query_emb, limit)?;

        let mut sections: Vec<String> = Vec::new();
        sections.push(format!(
            "# Mnemonic Context: \"{}\"\n\n_Auto-generated: {}_\n",
            topic,
            now.format("%Y-%m-%d %H:%M UTC")
        ));

        if similar.is_empty() {
            sections.push("No relevant memories found.".into());
        } else {
            // Also pull FTS results for broader coverage
            let fts_results = storage.search(topic, limit).unwrap_or_default();

            // Merge: similar first, then FTS additions
            let mut seen_ids: std::collections::HashSet<String> = std::collections::HashSet::new();
            let mut all_entries: Vec<(&MemoryEntry, Option<f32>)> = Vec::new();

            for (entry, sim) in &similar {
                seen_ids.insert(entry.id.clone());
                all_entries.push((entry, Some(*sim)));
            }
            for entry in &fts_results {
                if !seen_ids.contains(&entry.id) {
                    seen_ids.insert(entry.id.clone());
                    all_entries.push((entry, None));
                }
            }

            sections.push(format!(
                "## Relevant Memories ({} found)\n",
                all_entries.len()
            ));
            for (entry, sim) in &all_entries {
                let age = format_age(now, entry.timestamp);
                let sim_str = match sim {
                    Some(s) => format!(", sim: {s:.2}"),
                    None => String::new(),
                };
                sections.push(format!(
                    "- [{}] **{}** ({}{}) — {}",
                    entry.memory_type,
                    entry.title,
                    age,
                    sim_str,
                    truncate(&entry.content, 150),
                ));
                if !entry.tags.is_empty() {
                    sections.push(format!("  _tags: {}_", entry.tags.join(", ")));
                }
            }
        }

        let content = sections.join("\n");
        Ok(content)
    }

    fn write_file(&self, content: &str) -> Result<()> {
        if let Some(parent) = self.output_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&self.output_path, content)?;
        Ok(())
    }
}

fn format_age(now: chrono::DateTime<Utc>, timestamp: chrono::DateTime<Utc>) -> String {
    let diff = now - timestamp;
    let mins = diff.num_minutes();
    if mins < 60 {
        format!("{mins}m ago")
    } else if mins < 1440 {
        format!("{}h ago", mins / 60)
    } else {
        format!("{}d ago", mins / 1440)
    }
}

fn truncate(s: &str, max_chars: usize) -> String {
    let first_line = s.lines().next().unwrap_or(s);
    if first_line.chars().count() <= max_chars {
        first_line.to_string()
    } else {
        let truncated: String = first_line.chars().take(max_chars).collect();
        format!("{truncated}...")
    }
}
